### PR TITLE
Add 2021 parts 0,1 and distribution guide.

### PR DESCRIPTION
**Pull request by HexDecimal**
[Week 1 has started](https://www.reddit.com/r/roguelikedev/comments/oa2g5r/roguelikedev_does_the_complete_roguelike_tutorial/) and this is my rushed progress so far.  I'm not used to writing tutorials.

If you have time to look at the current progress and make suggestions then that'd be nice.  Otherwise this PR is just to let you know to update the website.

Also about updating the website: how is that done and can it be automated?

(I can implement diffs, it's just hard to justify them in part 1.)

### CODE REVIEW

**Comment by HexDecimal** [comment]
This isn't going to work right now.  I know you're busy and I don't think this is important enough to bother you with.  I should have discussed how I'd update the website much earlier.

I'll either host this somewhere else or postpone it for another time.

**Review by TStand90 — APPROVED** [review]

**Comment by TStand90** [comment]
Changes look good, I can merge them today. Later (latest this weekend) I'll set up an automated process to pull/publish the latest changes from the master branch automatically.

**Comment by HexDecimal** [comment]
I'm not really sure what to do.  I didn't give you much time to review the PR then I panicked when you didn't respond quickly.  I even have another website setup using GitHub Pages.

Being able to update the website by pushing to master is probably the most important part to me right now.  I can help with GitHub Actions if you need.

I don't like how my new part-1 turned out.  I could have put off the `actions` and `input_handlers` until the next part since they get refactored at that time anyway.

**Comment by TStand90** [comment]
GitHub Pages might be a better hosting solution for now, though I don't know a lot about it so I can't say for sure. I should be able to set up the auto-updates for the website without much trouble, the problem is more about time than difficulty. I'll see if I can squeeze in some time later today.

Writing a tutorial for the event while it's going on is difficult and time consuming (probably about 20-30 hours each week). I've done it twice now, and I was never happy with how either one turned out. The first one contains a ton of code and architecture I'm not proud of, and the second contains those middle-of-the-tutorial refactors since we changed things as the event was going on.

I can try helping out with writing some stuff this weekend, but I honestly can't promise much. This event kind of snuck up on me, and as much as I'd like to, I simply can't spend as much time on this as I have in past years. Lately I've been thinking about somehow transferring ownership/maintainership of all this by putting it in a more public place (like how the original Python tutorial is on roguebasin) due to how bad I am at maintaining and responding to issues. It might be this year since the event just started, but it's probably something that should be done by next year.

**Comment by HexDecimal** [comment]
GitHub Pages uses Jekyll which has been very similar to Hugo so far.  I'm able to copy my articles with few changes, I just need to mentally prepare.  You won't need to update your site.

I don't blame you for not having the time to help with this.  I'm hesitant do it this year myself.  This time it can be just me learning how to setup websites and write the articles, and that's fine.

As flawed as the current tutorials are each one has been better than the previous one.  I can assume I won't like the new tutorial nearly as much as everyone else always does.

I have [an organization called libtcod](https://github.com/libtcod) for libtcod-related projects.  I mostly used it to preserve what used to be on BitBucket before that went away.   You could transfer `libtcod/tcod_tutorial_v2` to `libtcod/tcod_tutorial_v2` if you like since I've mostly been working on that repo.  I'd also accept your other tutorials, but I'd likely just archive the older ones after fixing any easy issues.  Old tutorials won't be updated just because they're public. Someone would have to actively maintain them.

**Pull request closed without merging**
