### PR TITLE
Markdown conversion

### PR DESCRIPTION
**Pull request by FractalWire**
Hey !

So I thought instead of having raw html for the webpages, it would be nice to have markdown instead.
I find that much more readable, and editing it is no trouble at all, usually.

The only  possible difference (that I noticed) would be your use of `strikethrough` style in code snippet.
As an alternative, I've enabled Syntax Highlight and added `+/-` where there was a code style color before. That way, you can use the `diff` syntax highlighting to show... diff.
The only drawback is that a reader won't be able to simply copy/paste the code, but they still can do that at the end of the tutorial part so...

I used the `script.sh` to automatically do the conversion from html -> markdown.
It would still need some manual editing to enable `diff` syntax on the diffs code snippet. However, the part-1 has all the syntax required if you want to take a look.

Let me know what you think of this, and if markdown conversion is something you want.

### CODE REVIEW

**Comment by TStand90** [comment]
Wow, this is fantastic!

Converting to markdown is definitely the right way to go. I also like the way the diff looks versus the strike-through text, and the fact that the users can't copy/paste isn't a huge issue since they couldn't really do that anyway (because the strike-through text would get copied as well).

Only possible issue is that it messes with the indentation when the line isn't normally indented. For example, import statements. Any statements within an function would be fine, since they can be lined up by subtracting a space. The readers might have to understand that the indentation of these lines might not be perfect.

I'll see if I can find a solution for this.

**Comment by FractalWire** [comment]
So I modified the script a bit to reflect your comments.
Now, it is aligned with the rest of the code most of the time, except, as you noted, when this is an import statement or something with no preceding spaces. In that case, there is an additional `+/-` immediately before the code.

So, it does not mess anymore with indentation now.
I think it's fine, this is actually how the diffs look like on github for example.
This could be useful if you modify the code in your other repository, you could then just diff the changes and copy-paste it directly where you want in the tutorial.

If you add a small note mentionning that the prepending `+/-` are not to be copied in part 0 for example (or the first time you use a diff), the reader should hopefully understand.

**Comment by TStand90** [comment]
I think I've come up with a solution that should make everyone happy.

I've added a shortcode (Hugo's way of creating reusable components, as I understand it) to toggle between what I've called "diff" view and "original" view. The buttons to toggle appear over each relevant code section, but the toggle applies to the entire page. This was heavily inspired by (i.e. copied from) the code toggler on Hugo's documentation site.

Here's what that looks like:
diff-view

original-view

I've modified the CSS for the "original" view to look more like the diff one. The only real difference at this point is the + and - at the beginning of the line. Diff view makes it much more clear what is being added or subtracted, and the original view is a bit easier to copy and paste.

(Yeah, probably overkill, I know, but a lot of people like being able to copy and paste straight from the website, or so I've been told).

I've converted the first two parts so far and should be able to finish the rest within a day or two. I'm still using your markdown conversion for the actual pages themselves, which should be far easier to maintain.

Thanks again for this awesome submission! I doubt the markdown conversion would have ever happened otherwise.

**Comment by FractalWire** [comment]
Well, the "original" version looks fine to me. I used diff view because I find that conversion easy to do, but going the extra miles with custom CSS seems a good way to do it as well (if it's not too cumbersome when editing your tutorial).

So, honestly, I don't think you need to have 2 views, I find the "original" version clear enough.

In any case, I'm glad my little script could help :)

**Comment by TStand90** [comment]
I've merged your changes and included the diff version, because I think it's useful. It might be easier for some people to understand, especially people with vision impairments like color-blindness. Of course, the markdown conversion is great because it'll just be easier to maintain and update in the future.
Thanks again for your awesome contribution! I doubt the markdown conversion would have ever happened otherwise.

**Pull request merged**
